### ISSUE TITLE
Mechanical machines crash the game when blowing up

### ISSUE THREAD

**Issue by PatriikPlays** [Apioframe/eln1-revived#26]
Mechanical machines crash when blowing up.

I was testing mechanical stuff and accidentally placed a generator next to a running generator and the game crashed.

```
Time: 8/16/22 9:10 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at mods.eln.sim.Simulator.tick(Simulator.kt:492)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_8_Simulator_tick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:536)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by qrmcat** [comment]
It probably calls the destructImpl method directly, and not put it in the destructable list.

**Comment by qrmcat** [comment]
Should have fixed by https://github.com/V0xelTech/eln1-revived/commit/0004fc13882973b0b4de56ecba6bbaee72f9e03a
